baseurl: /
languageCode: en-US
title: Hyeseon Eom
theme: hugo-coder
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
permalinks:
  post: /:year/:month/:day/:slug/
menu:
  main:
    - name: "About"
      url: "/about/"
      weight: 1
    - name: "Researc"
      url: "/research/"
      weight: 2
    - name: "Landscape Design"
      url: "/landscape-design//"
      weight: 3
    - name: "Drawing"
      url: "/drawing/"
      weight: 4
params:
  homeInfoParams:
    Title: "Hi, I'm Hyeseon ðŸ‘‹"
    Content: >
      Landscape designer, urban ecology researcher, and more.
      Welcome to my portfolio!
  MathJaxCDN: //cdnjs.cloudflare.com/ajax/libs
  MathJaxVersion: 2.7.5
  description: A website built through Hugo and blogdown.
  favicon: favicon.ico
  highlightjsCDN: //cdnjs.cloudflare.com/ajax/libs
  highlightjsLang:
    - r
    - yaml
  highlightjsTheme: github
  highlightjsVersion: 9.12.0
  logo:
    alt: Logo
    height: 50
    url: logo.png
    width: 50
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: yes
  highlight:
    codeFences: no
